# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-jessie-node

    working_directory: ~/awbriggs.com

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - python-dependencies-{{ checksum "requirements.txt" }}
          - node-dependencies-{{ checksum "package.json" }}

      - run:
          name: install python dependencies
          command: sudo pip install -r requirements.txt

      - run:
          name: install npm dependencies
          command: npm install

      - save_cache:
          key: node-dependencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run:
          name: Make test directory
          command: mkdir -p test-reports/junit

      - run:
          name: run python tests
          command: python3  server/server/test/__init__.py

      - run:
          name: run jest test
          command: ./node_modules/.bin/jest --runInBand --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "test-reports/junit/js-test-results.xml"

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
