# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-jessie-node

    working_directory: ~/awbriggs.com

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - python-dependencies-{{ checksum "requirements.txt" }}
          - node-dependencies-{{ checksum "package.json" }}

      - run:
          name: install python dependencies
          command: sudo pip install -r requirements.txt

      - save_cache:
          key: python-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: install npm dependencies
          command: npm install

      - save_cache:
          key: node-dependencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run:
          name: run python tests
          command: python3 -m unittest discover -s server -p '*Test.py'

      - run:
          name: run jest test
          command: mkdir test-results && ./node_modules/.bin/jest --outputFile=test-results/jest

      - store_test_results:
          path: test-results
